services:
  fastapi:
    image: neojpulido/fastapi:dev
    #container_name: fastapi_dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  streamlit:
    image: neojpulido/streamlit:dev
    #container_name: streamlit_dev
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      API_URL: http://fastapi:8000
