apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: model
  name: model
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: model
    spec:
      containers:
      - image: neojpulido/fastapi:v2
        name: fastapi
        ports:
        - containerPort: 8000
        resources: {}
status: {}
